<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXxFxmMX\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXxFxmMX/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXxFxmMX.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXxFxmMX\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXxFxmMX\App_KernelDevDebugContainer([
    'container.build_hash' => 'XxFxmMX',
    'container.build_id' => 'cf565307',
    'container.build_time' => 1607977722,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXxFxmMX');
